import All from "@/components/all/all";
import Footer from "@/components/footer/footer";
import Hero from "@/components/hero/hero";
import NavBar from "@/components/navbar/nav";
import NavSmall from "@/components/navsmall/navsmall";
import Partner from "@/components/partner/partner";
import TopRecipe from "@/components/recipe/toprecipe";
import Review from "@/components/review/review";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>FoodFighters</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={
          "w-full h-screen font-inter overflow-x-hidden overflow-y-scroll max-w-full bg-white scroll-smooth"
        }
      >
        <NavBar />
        <NavSmall />
        <Hero />
        <All />
        <TopRecipe />
        <Review />
        <Partner />
        <Footer />{" "}
      </main>
    </>
  );
}
